---
title: "Cross Validation"
output: html_document
date: "2023-11-14"
---

Load key packages 
```{r}
library(tidyverse)
library(modelr)

set.seed(1)
```


## Nonlinear data and CV 
```{r}
nonlin_df = 
  tibble(
    id = 1:100, 
    x = runif(100, 0, 1), 
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

Do the train / test split 
```{r}
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df, train_df, by = "id")
```

```{r}
train_df |> 
  ggplot(aes(x=x, y=y)) + geom_point() + geom_point(data = test_df, color = "red")
```

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k=30), sp = 10e-6, data = train_df)
```

quick visualization of the linear model 
```{r}
train_df |> 
  modelr::add_predictions(wiggly_mod) |> 
  ggplot(aes(x = x, y = y)) + geom_point() + geom_line(aes(y=pred))
```


RMSE on testing data give misrepresentation of best fit 
```{r}
rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(wiggly_mod, train_df)

rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## Use modelr for CV 
```{r}
cv_df = 
  nonlin_df |> 
  crossv_mc(n = 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

```{r}
cv_df |> pull(train) |> nth(3) |> as_tibble()
```













