---
title: "linear_models"
output: html_document
date: "2023-11-09"
---

Load key packages 
```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location/2) |> 
  select(
    price, stars, borough = neighbourhood_group,
    neighbourhood, room_type) |> 
  filter(borough != "Staten Island")
```

Let's fit a model: 
```{r}
fit = nyc_airbnb |> 
  lm(price ~ stars + borough, data = _)
```

Let's look at the 'fit
```{r}
fit
summary(fit)
summary(fit)$coef
coef(fit)
#fitted.values(fit)
```

Now lets tidy the output instead: 
```{r}
fit |> 
  broom::glance()
```

Tidying the coefficients: 
```{r}
fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough:")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```

## Fit another model 
```{r}
fit = nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) |> 
  lm(price ~ stars + borough + room_type, data = _)

fit |> 
  broom::tidy()
```

## Quick look at diagnostics 
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin() 

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point() 
```


## Hypothesis Testing for Categorical Predictors 

Fit a null and alternative model: 
```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alt) |> 
  broom::tidy()
```

##Borough-level differences 
```{r}

```




